version: '3.1'

services:

  ahrulesbot:
    container_name: ahrulesbot
    image: flerkam/ah-rules-bot:latest
    volumes:
     - ./rules.json:/app/rules.json
     - ./google-cred.json:/app/google-cred.json.json
     - ./cards.json:/app/cards.json
    environment:
      AhRulesBot_TestChatId: "ID"
      AhRulesBot_AHChatId: "ID"
      AhRulesBot_BotAdminId: "ID"
      AhRulesBot_ApiKey: "KEY"
      AhRulesBot_BotName: "@MYBOT"
      AhRulesBot_GoogleCredFilePath: "filepath"
      AhRulesBot_GoogleFileId: "ID"
      AhRulesBot_CardsFilePath: "cards_json_location"
      AhRulesBot_RulesFilePath: "rules_json_location"
      AhRulesBot_NightAzStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_DunwichStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_CarcosaStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_ForgAgeStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_CircleUndoneStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_StandAloneStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_NotLocalStSpoilerIdTg: "telegram_file_id"
      AhRulesBot_NotNotLocalStSpoilerIdTg: "telegram_file_id"
    networks:
      - rpi
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

networks:
  rpi:
     external: true
