version: '3.1'

services:

  ahrulesbot:
    container_name: ahrulesbot
    image: flerkam/ah-rules-bot:latest
    volumes:
     - ./rules.json:/app/rules.json
    environment:
      AhRulesBot_TestChatId: "ID"
      AhRulesBot_AHChatId: "ID"
      AhRulesBot_BotAdminId: "ID"
      AhRulesBot_ApiKey: "KEY"
      AhRulesBot_BotName: "@MYBOT"
    networks:
      - rpi
    restart: unless-stopped
    logging:
        driver: "json-file"
        options:
            max-file: "5"
            max-size: "10m"

networks:
  rpi:
     external: true
